// // var employe={
// //     employeID:1273,
// //     // employePost:"CEO",
// //     // employesalary:"25k",
// //     employename:"Aarav",
// //     PhoneNumber:91238329
// }

var randomNo=Math.random()
randomNo=randomNo*10000000;
randomNo=Math.floor(randomNo);


// document.write(employe.employeID)
// document.write("<br>")
// document.write(employe.employePost)
// document.write("<br>")
// document.write(employe.employename)
// document.write("<br>")
// document.write(employe.employesalary)
// document.write("<br>")
// document.write(employe.PhoneNumber)
// document.write("<br>")
document.write(randomNo)

